version: '3.1'

services:
  backend:
    build: .
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
